#pragma once

struct BSPackedTask {
	enum QueuedTaskID
	{
		TASK_EXAMPLE_PRINT_FLOAT = 0x0,
		TASK_EXAMPLE_PRINT_INT = 0x1,
		TASK_SKY_EMITTANCE_UPDATE = 0x2,
		TASK_UNK_3 = 0x3,
		TASK_CELL_TRANSFORMS_UPDATE = 0x4,
		TASK_UNK_5 = 0x5,
		TASK_GEOMORPH_UPDATE = 0x6,
		TASK_ATTACH_NODE = 0x7,
		TASK_DETACH_NODE = 0x8,
		TASK_UNK_9 = 0x9,
		TASK_UPDATE_3D = 0xA,
		TASK_ACTOR_CREATEBLOOD = 0xB,
		TASK_DAMAGE_OBJECT = 0xC,
		TASK_UPDATE_DESTRUCTIBLEOBJECT = 0xD,
		TASK_KILL_ACTOR = 0xE,
		TASK_ACTOR_MELEEATTACK = 0xF,
		TASK_UNK_16 = 0x10,
		TASK_ACTOR_HITME = 0x11,
		TASK_MHE_INSTANTIATE_HIT_EFFECTS = 0x12,
		TASK_3D_HAVOKADD = 0x13,
		TASK_3D_HAVOKREMOVE = 0x14,
		TASK_ATTACH_WEAPON = 0x15,
		TASK_REMOVE_WEAPON = 0x16,
		TASK_SET_3D_NULL	= 0x17,
		TASK_ACTOR_DISMEMBER = 0x18,
		TASK_WATER_25 = 0x19,
		TASK_WATER_26 = 0x1A,
		TASK_ADD_OBSTACLE_DOOR_OPEN = 0x1B,
		TASK_ADD_OBSTACLE_DOOR_CLOSE = 0x1C,
		TASK_ACTOR_UPDATE_APPEARANCE = 0x1D,
		TASK_UNK_30 = 0x1E,
		TASK_MOVE_TO_MARKER = 0x1F,
		TASK_HANDLE_FIRED_WEAPON = 0x20,
		TASK_UNK_33 = 0x21,
		TASK_UNK_34 = 0x22,
		TASK_UNK_35 = 0x23,
		TASK_WATER_SPLASH_EFFECTS = 0x24,
		TASK_WATER_ADD_RIPPLE = 0x25,
		TASK_ACTOR_TRIGGERPAIN = 0x26,
		TASK_ACTOR_APPLYCRITSTAGE = 0x27,
		TASK_UNK_40 = 0x28,
		TASK_UNK_41 = 0x29,
		TASK_UNLOAD_3D = 0x2A,
		TASK_UNK_43 = 0x2B,
		TASK_ACTOR_SETPOSITION = 0x2C,
		TASK_HAVOKINIT = 0x2D,
		TASK_UNK_46 = 0x2E,
		TASK_UNK_47 = 0x2F,
		TASK_REMOVE_PICKEDUP_OBJECT = 0x30,
		TASK_UNK_49 = 0x31,
	};

	union Data {
		bool	bData;
		char	cDataA[4];
		UInt16	usDataA[2];
		SInt32	iData;
		float	fData;
		void*	pData;
		UInt32	uiData;
	};

	BSPackedTask();
	~BSPackedTask();

	Data Data[8];

	const char* GetTaskName() const;
	void SetTaskThreadName(HANDLE apThread) const;
};

STATIC_ASSERT(sizeof(BSPackedTask) == 0x20);