#pragma once

#include "NiColor.hpp"
#include "NiPoint2.hpp"
#include "NiPoint3.hpp"
#include "NiPoint4.hpp"
#include "NiTexture.hpp"
#include "NiSourceTexture.hpp"
#include "NiRenderedTexture.hpp"
#include "NiRenderedCubeMap.hpp"
#include "NiTStringMap.hpp"
#include "NiRect.hpp"
#include "NiLight.hpp"
#include "NiTexturingProperty.hpp"
#include "NiGeometry.hpp"

#define USE_PBR 0

class BSShader;
class ShadowSceneNode;
class BSRenderedTexture;
class BSShaderAccumulator;
class NiDX9Renderer;
class TangentSpaceData;

class BSShaderManager {
public:
	enum SceneGraphType : UInt32 {
		BSSM_SSN_WORLD			= 0,
		BSSM_SSN_MENU_OBJECT_3D = 1,
		BSSM_SSN_UNK_2			= 2,
		BSSM_SSN_MENU_PLAYER_3D = 3,
		BSSM_SSN_COUNT			= 4,
	};

	enum ShaderType : UInt32 {
		BSSM_SHADER_DEFAULT			= 0,
		BSSM_SHADER_SHADOWLIGHT		= 1,
		BSSM_SHADER_TALL_GRASS		= 2,
		BSSM_SHADER_DISTANT_LOD		= 3,
		BSSM_SHADER_ST_BRANCH		= 4,
		BSSM_SHADER_ST_FROND		= 5,
		BSSM_SHADER_ST_LEAF			= 6,
		BSSM_SHADER_BLOOD_SPLATTER	= 7,
		BSSM_SHADER_DISTANT_TREE	= 8,
		BSSM_SHADER_DEBUG			= 9,
		BSSM_SHADER_SKY				= 10,
		//							  11
		//							  12
		BSSM_SHADER_HAIR			= 13,
		BSSM_SHADER_SKIN			= 14,
		BSSM_SHADER_PARALLAX		= 15,
		BSSM_SHADER_GEOM_DECAL		= 16,
		BSSM_SHADER_WATER			= 17,
		// 							  18
		// 							  19
		// 							  20
		// 							  21
		// 							  22
		// 							  23
		BSSM_SHADER_PARTICLE		= 24,
		BSSM_SHADER_BOLT			= 25,
		BSSM_SHADER_BEAM			= 26,
		//							  27
		//							  28
		BSSM_SHADER_LIGHTING30		= 29,
		BSSM_SHADER_PRECIPITATION	= 30,
		// 							  31
		BSSM_SHADER_TILE			= 32,
		BSSM_SHADER_NOLIGHTING		= 33,
		BSSM_SHADER_VOLUMETRIC_FOG	= 34,
	};

	enum RenderPassType : UInt32 {
		BSSM_EMPTY																= 0,
		BSSM_ZONLY																= 1,
		BSSM_ZONLY_At															= 2,
		BSSM_ZONLY_S															= 3,
		BSSM_ZONLY_TEXEFFECT													= 4,
		BSSM_ZONLY_TEXEFFECT_S													= 5,
		BSSM_CONSTALPHA															= 6,
		BSSM_CONSTALPHA_At														= 7,
		BSSM_CONSTALPHA_S														= 8,
		BSSM_AMBIENT_OCCLUSION													= 9,
		BSSM_3XZONLY															= 10,
		BSSM_3XZONLY_S															= 11,
		BSSM_3XZONLY_Vc															= 12,
		BSSM_3XZONLY_SVc														= 13,
		BSSM_3XZONLY_TEXEFFECT													= 14,
		BSSM_3XZONLY_TEXEFFECT_S												= 15,
		BSSM_DEPTHMAP															= 16,
		BSSM_DEPTHMAP_At														= 17,
		BSSM_DEPTHMAP_S															= 18,
		BSSM_DEPTHMAP_SAt														= 19,
		BSSM_SELFILLUMALPHABLOCK												= 20,
		BSSM_SELFILLUMALPHABLOCK_S												= 21,
		BSSM_GRASS_NOALPHA_DIRONLY_LF											= 22,
		BSSM_GRASS_NOALPHA_DIRONLY_LV											= 23,
		BSSM_GRASS_NOALPHA_DIRONLY_LFS											= 24,
		BSSM_GRASS_NOALPHA_DIRONLY_LVS											= 25,
		BSSM_GRASS_NOALPHA_DIRONLY_LFP											= 26,
		BSSM_GRASS_NOALPHA_DIRONLY_LVP											= 27,
		BSSM_GRASS_NOALPHA_DIRONLY_LFSP											= 28,
		BSSM_GRASS_NOALPHA_DIRONLY_LVSP											= 29,
		BSSM_GRASS_NOALPHA_DIRONLY_LFShp										= 30,
		BSSM_GRASS_NOALPHA_DIRONLY_LVShp										= 31,
		BSSM_GRASS_NOALPHA_DIRONLY_LFSShp										= 32,
		BSSM_GRASS_NOALPHA_DIRONLY_LVSShp										= 33,
		BSSM_GRASS_NOALPHA_DIRONLY_LFPShp										= 34,
		BSSM_GRASS_NOALPHA_DIRONLY_LVPShp										= 35,
		BSSM_GRASS_NOALPHA_DIRONLY_LFSPShp										= 36,
		BSSM_GRASS_NOALPHA_DIRONLY_LVSPShp										= 37,
		BSSM_GRASS_NOALPHA_DIRONLY_LFB											= 38,
		BSSM_GRASS_NOALPHA_DIRONLY_LFSB											= 39,
		BSSM_GRASS_NOALPHA_DIRONLY_LFPB											= 40,
		BSSM_GRASS_NOALPHA_DIRONLY_LFSPB										= 41,
		BSSM_GRASS_NOALPHA_1POINT_LF											= 42,
		BSSM_GRASS_NOALPHA_1POINT_LV											= 43,
		BSSM_GRASS_NOALPHA_1POINT_LFS											= 44,
		BSSM_GRASS_NOALPHA_1POINT_LVS											= 45,
		BSSM_GRASS_NOALPHA_1POINT_LFP											= 46,
		BSSM_GRASS_NOALPHA_1POINT_LVP											= 47,
		BSSM_GRASS_NOALPHA_1POINT_LFSP											= 48,
		BSSM_GRASS_NOALPHA_1POINT_LVSP											= 49,
		BSSM_GRASS_NOALPHA_1POINT_LFShp											= 50,
		BSSM_GRASS_NOALPHA_1POINT_LVShp											= 51,
		BSSM_GRASS_NOALPHA_1POINT_LFSShp										= 52,
		BSSM_GRASS_NOALPHA_1POINT_LVSShp										= 53,
		BSSM_GRASS_NOALPHA_1POINT_LFPShp										= 54,
		BSSM_GRASS_NOALPHA_1POINT_LVPShp										= 55,
		BSSM_GRASS_NOALPHA_1POINT_LFSPShp										= 56,
		BSSM_GRASS_NOALPHA_1POINT_LVSPShp										= 57,
		BSSM_GRASS_NOALPHA_1POINT_LFB											= 58,
		BSSM_GRASS_NOALPHA_1POINT_LFSB											= 59,
		BSSM_GRASS_NOALPHA_1POINT_LFPB											= 60,
		BSSM_GRASS_NOALPHA_1POINT_LFSPB											= 61,
		BSSM_LEAVES_AD															= 62,
		BSSM_LEAVES_ADPt														= 63,
		BSSM_FRONDS																= 64,
		BSSM_PARTICLE_PREPASS													= 65,
		BSSM_NOLIGHTING															= 66,
		BSSM_NOLIGHTING_VC														= 67,
		BSSM_NOLIGHTING_TexVC													= 68,
		BSSM_NOLIGHTING_MAT														= 69,
		BSSM_NOLIGHTING_S														= 70,
		BSSM_NOLIGHTING_VC_S													= 71,
		BSSM_NOLIGHTING_TexVC_S													= 72,
		BSSM_NOLIGHTING_MAT_S													= 73,
		BSSM_NOLIGHTING_FALLOFF													= 74,
		BSSM_NOLIGHTING_VC_FALLOFF												= 75,
		BSSM_NOLIGHTING_TexVC_FALLOFF											= 76,
		BSSM_NOLIGHTING_MAT_FALLOFF												= 77,
		BSSM_NOLIGHTING_FALLOFF_S												= 78,
		BSSM_NOLIGHTING_VC_FALLOFF_S											= 79,
		BSSM_NOLIGHTING_TexVC_FALLOFF_S											= 80,
		BSSM_NOLIGHTING_MAT_FALLOFF_S											= 81,
		BSSM_NOLIGHTING_PSYS													= 82,
		BSSM_NOLIGHTING_PSYS_SUBTEX_OFFSET										= 83,
		BSSM_NOLIGHTING_PSYS_PREMULT_ALPHA										= 84,
		BSSM_NOLIGHTING_PSYS_SUBTEX_OFFSET_PREMULT_ALPHA						= 85,
		BSSM_NOLIGHTING_STRIP_PSYS												= 86,
		BSSM_NOLIGHTING_STRIP_PSYS_SUBTEX										= 87,
		BSSM_AMBIENT															= 88,
		BSSM_AMBIENT_G															= 89,
		BSSM_AMBIENT_At															= 90,
		BSSM_AMBIENT_GAt														= 91,
		BSSM_AMBIENT_S															= 92,
		BSSM_AMBIENT_SG															= 93,
		BSSM_AMBIENT_SAt														= 94,
		BSSM_AMBIENT_SGAt														= 95,
		BSSM_AMBIENT_Sb															= 96,
		BSSM_AMBIENT_Mn															= 97,
		BSSM_AMBIENT_F															= 98,
		BSSM_AMBIENT_FAt														= 99,
		BSSM_AMBDIFFTEX															= 100,
		BSSM_AMBDIFFTEX_Vc														= 101,
		BSSM_AMBDIFFTEX_G														= 102,
		BSSM_AMBDIFFTEX_GVc														= 103,
		BSSM_AMBDIFFTEX_Fg														= 104,
		BSSM_AMBDIFFTEX_A														= 105,
		BSSM_AMBDIFFTEX_AVc														= 106,
		BSSM_AMBDIFFTEX_GA														= 107,
		BSSM_AMBDIFFTEX_GAVc													= 108,
		BSSM_AMBDIFFTEX_FgA														= 109,
		BSSM_AMBDIFFTEX_GFgA													= 110,
		BSSM_AMBDIFFTEX_S														= 111,
		BSSM_AMBDIFFTEX_SVc														= 112,
		BSSM_AMBDIFFTEX_SG														= 113,
		BSSM_AMBDIFFTEX_SGVc													= 114,
		BSSM_AMBDIFFTEX_SFg														= 115,
		BSSM_AMBDIFFTEX_SA														= 116,
		BSSM_AMBDIFFTEX_SAVc													= 117,
		BSSM_AMBDIFFTEX_SGA														= 118,
		BSSM_AMBDIFFTEX_SGAVc													= 119,
		BSSM_AMBDIFFTEX_SFgA													= 120,
		BSSM_AMBDIFFTEX_SGFgA													= 121,
		BSSM_AMBDIFFTEX_Sb														= 122,
		BSSM_AMBDIFFTEX_SbF														= 123,
		BSSM_AMBDIFFDIRANDPT													= 124,
		BSSM_AMBDIFFDIRANDPT_S													= 125,
		BSSM_AMBDIFFDIRANDPT_Sb													= 126,
		BSSM_AMBDIFFTEX_F														= 127,
		BSSM_AMBDIFFTEX_FVc														= 128,
		BSSM_AMBDIFFTEX_FG														= 129,
		BSSM_AMBDIFFTEX_FGVc													= 130,
		BSSM_AMBDIFFTEX_FA														= 131,
		BSSM_AMBDIFFTEX_FAVc													= 132,
		BSSM_AMBDIFFTEX_FFg														= 133,
		BSSM_AMBDIFFTEX_FGA														= 134,
		BSSM_AMBDIFFTEX_FGAVc													= 135,
		BSSM_AMBDIFFTEX_FGFgA													= 136,
		BSSM_AMBDIFFTEX_SF														= 137,
		BSSM_AMBDIFFTEX_SFVc													= 138,
		BSSM_AMBDIFFTEX_SFG														= 139,
		BSSM_AMBDIFFTEX_SFGVc													= 140,
		BSSM_AMBDIFFTEX_SFA														= 141,
		BSSM_AMBDIFFTEX_SFAVc													= 142,
		BSSM_AMBDIFFTEX_SFFg													= 143,
		BSSM_AMBDIFFTEX_SFGA													= 144,
		BSSM_AMBDIFFTEX_SFGAVc													= 145,
		BSSM_AMBDIFFTEX_SFGFgA													= 146,
		BSSM_LANDAD																= 147,
		BSSM_LANDAD_Shp															= 148,
		BSSM_ADTS																= 149,
		BSSM_ADTS_G																= 150,
		BSSM_ADTS_H																= 151,
		BSSM_ADTS_Fg															= 152,
		BSSM_ADTS_Px															= 153,
		BSSM_ADTS_GPx															= 154,
		BSSM_ADTS_S																= 155,
		BSSM_ADTS_SG															= 156,
		BSSM_ADTS_SH															= 157,
		BSSM_ADTS_SFg															= 158,
		BSSM_ADTS_Sb															= 159,
		BSSM_ADTS_Shp															= 160,
		BSSM_ADTS_GShp															= 161,
		BSSM_ADTS_HShp															= 162,
		BSSM_ADTS_FgShp															= 163,
		BSSM_ADTS_PxShp															= 164,
		BSSM_ADTS_GPxShp														= 165,
		BSSM_ADTS_SShp															= 166,
		BSSM_ADTS_SGShp															= 167,
		BSSM_ADTS_SHShp															= 168,
		BSSM_ADTS_SFgShp														= 169,
		BSSM_ADTS_SbShp															= 170,
		BSSM_ADTS2																= 171,
		BSSM_ADTS2_G															= 172,
		BSSM_ADTS2_H															= 173,
		BSSM_ADTS2_Fg															= 174,
		BSSM_ADTS2_Px															= 175,
		BSSM_ADTS2_GPx															= 176,
		BSSM_ADTS2_S															= 177,
		BSSM_ADTS2_SG															= 178,
		BSSM_ADTS2_SH															= 179,
		BSSM_ADTS2_SFg															= 180,
		BSSM_ADTS2_Sb															= 181,
		BSSM_ADTS2_Shp															= 182,
		BSSM_ADTS2_GShp															= 183,
		BSSM_ADTS2_HShp															= 184,
		BSSM_ADTS2_FgShp														= 185,
		BSSM_ADTS2_PxShp														= 186,
		BSSM_ADTS2_GPxShp														= 187,
		BSSM_ADTS2_SShp															= 188,
		BSSM_ADTS2_SGShp														= 189,
		BSSM_ADTS2_SHShp														= 190,
		BSSM_ADTS2_SFgShp														= 191,
		BSSM_ADTS2_SbShp														= 192,
		BSSM_ADTS_ONELIGHT														= 193,
		BSSM_ADTS_DIRANDPT														= 194,
		BSSM_ADT10																= 195,
		BSSM_ADT10_G															= 196,
		BSSM_ADT10_Fg															= 197,
		BSSM_ADT10_S															= 198,
		BSSM_ADT10_SG															= 199,
		BSSM_ADT10_SFg															= 200,
		BSSM_ADT4																= 201,
		BSSM_ADT4_Opt															= 202,
		BSSM_ADT4_G																= 203,
		BSSM_ADT4_Fg															= 204,
		BSSM_ADT4_S																= 205,
		BSSM_ADT4_SG															= 206,
		BSSM_ADT4_SFg															= 207,
		BSSM_ADTS10																= 208,
		BSSM_ADTS10_Opt															= 209,
		BSSM_ADTS10_G															= 210,
		BSSM_ADTS10_Fg															= 211,
		BSSM_ADTS10_S															= 212,
		BSSM_ADTS10_SG															= 213,
		BSSM_ADTS10_SFg															= 214,
		BSSM_AD2																= 215,
		BSSM_AD2_G																= 216,
		BSSM_AD2_Px																= 217,
		BSSM_AD2_GPx															= 218,
		BSSM_AD2_Fg																= 219,
		BSSM_AD2_S																= 220,
		BSSM_AD2_SG																= 221,
		BSSM_AD2_SFg															= 222,
		BSSM_AD2_Sb																= 223,
		BSSM_AD2_Shp															= 224,
		BSSM_AD2_GShp															= 225,
		BSSM_AD2_PxShp															= 226,
		BSSM_AD2_GPxShp															= 227,
		BSSM_AD2_FgShp															= 228,
		BSSM_AD2_SShp															= 229,
		BSSM_AD2_SGShp															= 230,
		BSSM_AD2_SFgShp															= 231,
		BSSM_AD2_SbShp															= 232,
		BSSM_AD3																= 233,
		BSSM_AD3_G																= 234,
		BSSM_AD3_Px																= 235,
		BSSM_AD3_GPx															= 236,
		BSSM_AD3_Fg																= 237,
		BSSM_AD3_S																= 238,
		BSSM_AD3_SG																= 239,
		BSSM_AD3_SFg															= 240,
		BSSM_AD3_Sb																= 241,
		BSSM_AD3_Shp															= 242,
		BSSM_AD3_GShp															= 243,
		BSSM_AD3_PxShp															= 244,
		BSSM_AD3_GPxShp															= 245,
		BSSM_AD3_FgShp															= 246,
		BSSM_AD3_SShp															= 247,
		BSSM_AD3_SGShp															= 248,
		BSSM_AD3_SFgShp															= 249,
		BSSM_AD3_SbShp															= 250,
		BSSM_ADT																= 251,
		BSSM_ADT_Opt															= 252,
		BSSM_ADT_OptLOD															= 253,
		BSSM_ADT_Mn																= 254,
		BSSM_ADT_G																= 255,
		BSSM_ADT_Fg																= 256,
		BSSM_ADT_Px																= 257,
		BSSM_ADT_PxOpt															= 258,
		BSSM_ADT_GPx															= 259,
		BSSM_ADT_H																= 260,
		BSSM_ADT_S																= 261,
		BSSM_ADT_SG																= 262,
		BSSM_ADT_SFg															= 263,
		BSSM_ADT_Sb																= 264,
		BSSM_ADT_SH																= 265,
		BSSM_ADT_Shp															= 266,
		BSSM_ADT_MnShp															= 267,
		BSSM_ADT_GShp															= 268,
		BSSM_ADT_FgShp															= 269,
		BSSM_ADT_PxShp															= 270,
		BSSM_ADT_GPxShp															= 271,
		BSSM_ADT_HShp															= 272,
		BSSM_ADT_SShp															= 273,
		BSSM_ADT_SGShp															= 274,
		BSSM_ADT_SFgShp															= 275,
		BSSM_ADT_SbShp															= 276,
		BSSM_ADT_SHShp															= 277,
		BSSM_ADT2																= 278,
		BSSM_ADT2_G																= 279,
		BSSM_ADT2_Fg															= 280,
		BSSM_ADT2_Px															= 281,
		BSSM_ADT2_GPx															= 282,
		BSSM_ADT2_H																= 283,
		BSSM_ADT2_S																= 284,
		BSSM_ADT2_SG															= 285,
		BSSM_ADT2_SFg															= 286,
		BSSM_ADT2_Sb															= 287,
		BSSM_ADT2_SH															= 288,
		BSSM_ADT2_Shp															= 289,
		BSSM_ADT2_GShp															= 290,
		BSSM_ADT2_FgShp															= 291,
		BSSM_ADT2_PxShp															= 292,
		BSSM_ADT2_GPxShp														= 293,
		BSSM_ADT2_HShp															= 294,
		BSSM_ADT2_SShp															= 295,
		BSSM_ADT2_SGShp															= 296,
		BSSM_ADT2_SFgShp														= 297,
		BSSM_ADT2_SbShp															= 298,
		BSSM_ADT2_SHShp															= 299,
		BSSM_DIFFUSEDIR															= 300,
		BSSM_DIFFUSEPT															= 301,
		BSSM_DIFFUSEDIR_S														= 302,
		BSSM_DIFFUSEPT_S														= 303,
		BSSM_DIFFUSEDIR_Sb														= 304,
		BSSM_DIFFUSEPT_Sb														= 305,
		BSSM_DIFFUSEPT2															= 306,
		BSSM_DIFFUSEPT2_Fg														= 307,
		BSSM_DIFFUSEPT2_Px														= 308,
		BSSM_DIFFUSEPT2_S														= 309,
		BSSM_DIFFUSEPT2_SFg														= 310,
		BSSM_DIFFUSEPT2_Sb														= 311,
		BSSM_DIFFUSEPT2_Shp														= 312,
		BSSM_DIFFUSEPT2_FgShp													= 313,
		BSSM_DIFFUSEPT2_PxShp													= 314,
		BSSM_DIFFUSEPT2_SShp													= 315,
		BSSM_DIFFUSEPT2_SFgShp													= 316,
		BSSM_DIFFUSEPT2_SbShp													= 317,
		BSSM_DIFFUSEPT3															= 318,
		BSSM_DIFFUSEPT3_Fg														= 319,
		BSSM_DIFFUSEPT3_Px														= 320,
		BSSM_DIFFUSEPT3_S														= 321,
		BSSM_DIFFUSEPT3_SFg														= 322,
		BSSM_DIFFUSEPT3_Sb														= 323,
		BSSM_DIFFUSEPT3_Shp														= 324,
		BSSM_DIFFUSEPT3_FgShp													= 325,
		BSSM_DIFFUSEPT3_PxShp													= 326,
		BSSM_DIFFUSEPT3_SShp													= 327,
		BSSM_DIFFUSEPT3_SFgShp													= 328,
		BSSM_DIFFUSEPT3_SbShp													= 329,
		BSSM_TEXTURE															= 330,
		BSSM_TEXTURE_Fg															= 331,
		BSSM_TEXTURE_H															= 332,
		BSSM_TEXTURE_S															= 333,
		BSSM_TEXTURE_Vc															= 334,
		BSSM_TEXTURE_SVc														= 335,
		BSSM_TEXTURE_SFg														= 336,
		BSSM_TEXTURE_Sb															= 337,
		BSSM_TEXTURE_SH															= 338,
		BSSM_TEXTURE_Px															= 339,
		BSSM_SPECULARDIR														= 340,
		BSSM_SPECULARPT															= 341,
		BSSM_SPECULARDIR_S														= 342,
		BSSM_SPECULARPT_S														= 343,
		BSSM_UNK_344															= 344,
		BSSM_UNK_345															= 345,
		BSSM_2x_SPECULARDIR														= 346,
		BSSM_2x_SPECULARDIR_H													= 347,
		BSSM_2x_SPECULARDIR_Px													= 348,
		BSSM_2x_SPECULARDIR_S													= 349,
		BSSM_2x_SPECULARDIR_SH													= 350,
		BSSM_2x_SPECULARDIR_Sb													= 351,
		BSSM_2x_SPECULARDIR_Shp													= 352,
		BSSM_2x_SPECULARDIR_HShp												= 353,
		BSSM_2x_SPECULARDIR_PxShp												= 354,
		BSSM_2x_SPECULARDIR_SShp												= 355,
		BSSM_2x_SPECULARDIR_SHShp												= 356,
		BSSM_2x_SPECULARDIR_SbShp												= 357,
		BSSM_2x_SPECULARPT														= 358,
		BSSM_2x_SPECULARPT_H													= 359,
		BSSM_2x_SPECULARPT_Px													= 360,
		BSSM_2x_SPECULARPT_S													= 361,
		BSSM_2x_SPECULARPT_SH													= 362,
		BSSM_2x_SPECULARPT_Sb													= 363,
		BSSM_2x_SPECULARPT2														= 364,
		BSSM_2x_SPECULARPT2_H													= 365,
		BSSM_2x_SPECULARPT2_Px													= 366,
		BSSM_2x_SPECULARPT2_S													= 367,
		BSSM_2x_SPECULARPT2_SH													= 368,
		BSSM_2x_SPECULARPT2_Sb													= 369,
		BSSM_2x_SPECULARPT3														= 370,
		BSSM_2x_SPECULARPT3_H													= 371,
		BSSM_2x_SPECULARPT3_Px													= 372,
		BSSM_2x_SPECULARPT3_S													= 373,
		BSSM_2x_SPECULARPT3_SH													= 374,
		BSSM_2x_SPECULARPT3_Sb													= 375,
		BSSM_3XOCCLUSION														= 376,
		BSSM_UNK_377															= 377,
		BSSM_UNK_378															= 378,
		BSSM_UNK_379															= 379,
		BSSM_UNK_380															= 380,
		BSSM_UNK_381															= 381,
		BSSM_UNK_382															= 382,
		BSSM_3XLIGHTING															= 383,
		BSSM_3XLIGHTING_S														= 384,
		BSSM_3XLIGHTING_H														= 385,
		BSSM_3XLIGHTING_Px														= 386,
		BSSM_3XLIGHTING_Pxo														= 387,
		BSSM_3XLIGHTING_Fg														= 388,
		BSSM_3XLIGHTING_SFg														= 389,
		BSSM_3XLIGHTING_G														= 390,
		BSSM_3XLIGHTING_SG														= 391,
		BSSM_3XLIGHTING_Vc														= 392,
		BSSM_3XLIGHTING_VcS														= 393,
		BSSM_3XLIGHTING_VcPx													= 394,
		BSSM_3XLIGHTING_VcPxo													= 395,
		BSSM_3XLIGHTING_VcG														= 396,
		BSSM_3XLIGHTING_VcSG													= 397,
		BSSM_3XLIGHTING_Spc														= 398,
		BSSM_3XLIGHTING_SSpc													= 399,
		BSSM_3XLIGHTING_HSpc													= 400,
		BSSM_3XLIGHTING_PxSpc													= 401,
		BSSM_3XLIGHTING_PxoSpc													= 402,
		BSSM_3XLIGHTING_FgSpc													= 403,
		BSSM_3XLIGHTING_SFgSpc													= 404,
		BSSM_3XLIGHTING_GSpc													= 405,
		BSSM_3XLIGHTING_SGSpc													= 406,
		BSSM_3XLIGHTING_VcSpc													= 407,
		BSSM_3XLIGHTING_VcSSpc													= 408,
		BSSM_3XLIGHTING_VcPxSpc													= 409,
		BSSM_3XLIGHTING_VcPxoSpc												= 410,
		BSSM_3XLIGHTING_VcGSpc													= 411,
		BSSM_3XLIGHTING_VcSGSpc													= 412,
		BSSM_3XLIGHTING_Shp														= 413,
		BSSM_3XLIGHTING_SShp													= 414,
		BSSM_3XLIGHTING_HShp													= 415,
		BSSM_3XLIGHTING_PxShp													= 416,
		BSSM_3XLIGHTING_PxoShp													= 417,
		BSSM_3XLIGHTING_FgShp													= 418,
		BSSM_3XLIGHTING_SFgShp													= 419,
		BSSM_3XLIGHTING_GShp													= 420,
		BSSM_3XLIGHTING_SGShp													= 421,
		BSSM_3XLIGHTING_VcShp													= 422,
		BSSM_3XLIGHTING_VcSShp													= 423,
		BSSM_3XLIGHTING_VcPxShp													= 424,
		BSSM_3XLIGHTING_VcPxoShp												= 425,
		BSSM_3XLIGHTING_VcGShp													= 426,
		BSSM_3XLIGHTING_VcSGShp													= 427,
		BSSM_3XLIGHTING_ShpSpc													= 428,
		BSSM_3XLIGHTING_SShpSpc													= 429,
		BSSM_3XLIGHTING_HShpSpc													= 430,
		BSSM_3XLIGHTING_PxShpSpc												= 431,
		BSSM_3XLIGHTING_PxoShpSpc												= 432,
		BSSM_3XLIGHTING_FgShpSpc												= 433,
		BSSM_3XLIGHTING_SFgShpSpc												= 434,
		BSSM_3XLIGHTING_GShpSpc													= 435,
		BSSM_3XLIGHTING_SGShpSpc												= 436,
		BSSM_3XLIGHTING_VcShpSpc												= 437,
		BSSM_3XLIGHTING_VcSShpSpc												= 438,
		BSSM_3XLIGHTING_VcPxShpSpc												= 439,
		BSSM_3XLIGHTING_VcPxoShpSpc												= 440,
		BSSM_3XLIGHTING_VcGShpSpc												= 441,
		BSSM_3XLIGHTING_VcSGShpSpc												= 442,
		BSSM_3XSILHOUETTE														= 443,
		BSSM_3XSILHOUETTE_Vc													= 444,
		BSSM_3XENVMAP															= 445,
		BSSM_3XENVMAP_W															= 446,
		BSSM_3XENVMAP_Vc														= 447,
		BSSM_3XENVMAP_WVc														= 448,
		BSSM_3XENVMAP_S															= 449,
		BSSM_3XENVMAP_SVc														= 450,
		BSSM_3XENVMAP_EYE														= 451,
		BSSM_3XLIGHTING_SIMPLESHADOW											= 452,
		BSSM_3XLIGHTING_SIMPLESHADOW_Vc											= 453,
		BSSM_3XLIGHTING_SIMPLESHADOW_S											= 454,
		BSSM_3XLIGHTING_SIMPLESHADOW_VcS										= 455,
		BSSM_3XDEPTHMAP															= 456,
		BSSM_3XDEPTHMAP_Vc														= 457,
		BSSM_3XDEPTHMAP_S														= 458,
		BSSM_3XDEPTHMAP_VcS														= 459,
		BSSM_3XRENDERNORMALS													= 460,
		BSSM_3XRENDERNORMALS_Vc													= 461,
		BSSM_3XRENDERNORMALS_S													= 462,
		BSSM_3XRENDERNORMALS_VcS												= 463,
		BSSM_3XRENDERNORMALS_FIRE												= 464,
		BSSM_3XRENDERNORMALS_CLEAR												= 465,
		BSSM_3XRENDERNORMALS_CLEAR_S											= 466,
		BSSM_3XCONSTALPHA														= 467,
		BSSM_3XCONSTALPHA_Vc													= 468,
		BSSM_3XCONSTALPHA_S														= 469,
		BSSM_3XCONSTALPHA_SVc													= 470,
		BSSM_3XDEPTH															= 471,
		BSSM_3XDEPTH_Vc															= 472,
		BSSM_3XDEPTH_S															= 473,
		BSSM_3XDEPTH_SVc														= 474,
		BSSM_3XVELOCITY															= 475,
		BSSM_3XVELOCITY_S														= 476,
		BSSM_3XLOCALMAP															= 477,
		BSSM_3XLOCALMAP_S														= 478,
		BSSM_3XLOCALMAP_CLEAR													= 479,
		BSSM_3XTEXEFFECT														= 480,
		BSSM_3XTEXEFFECT_S														= 481,
		BSSM_RENDERNORMALS														= 482,
		BSSM_RENDERNORMALS_S													= 483,
		BSSM_RENDERNORMALS_FIRE													= 484,
		BSSM_RENDERNORMALS_CLEAR												= 485,
		BSSM_RENDERNORMALS_CLEAR_S												= 486,
		BSSM_DEPTH																= 487,
		BSSM_DEPTH_S															= 488,
		BSSM_DEPTH_Mn															= 489,
		BSSM_VELOCITY															= 490,
		BSSM_VELOCITY_S															= 491,
		BSSM_LOCALMAP															= 492,
		BSSM_LOCALMAP_S															= 493,
		BSSM_LOCALMAP_CLEAR														= 494,
		BSSM_LANDDIFF															= 495,
		BSSM_LAND2xDIFF															= 496,
		BSSM_LAND_G																= 497,
		BSSM_LANDAD_A															= 498,
		BSSM_LANDAD_AShp														= 499,
		BSSM_LAND_GA															= 500,
		BSSM_LANDDIFF_A															= 501,
		BSSM_LAND2xDIFF_A														= 502,
		BSSM_LAND1O																= 503,	
		BSSM_LAND1O_Shp															= 504,
		BSSM_LAND1O_Simple														= 505,
		BSSM_LAND1O_SimpleShp													= 506,
		BSSM_LAND1O4															= 507,
		BSSM_LAND1O4_Shp														= 508,
		BSSM_LAND1O4_Simple														= 509,
		BSSM_LAND1O4_SimpleShp													= 510,
		BSSM_LAND2O																= 511,
		BSSM_LAND2O_Shp															= 512,
		BSSM_LAND2O_Simple														= 513,
		BSSM_LAND2O_SimpleShp													= 514,
		BSSM_LAND2O4															= 515,
		BSSM_LAND2O4_Shp														= 516,
		BSSM_LAND2O4_Simple														= 517,
		BSSM_LAND2O4_SimpleShp													= 518,
		BSSM_LAND3O																= 519,
		BSSM_LAND3O_Shp															= 520,
		BSSM_LAND3O_Simple														= 521,
		BSSM_LAND3O_SimpleShp													= 522,
		BSSM_LAND3O4															= 523,
		BSSM_LAND3O4_Shp														= 524,
		BSSM_LAND3O4_Simple														= 525,
		BSSM_LAND3O4_SimpleShp													= 526,
		BSSM_LAND4O																= 527,
		BSSM_LAND4O_Shp															= 528,
		BSSM_LAND4O_Simple														= 529,
		BSSM_LAND4O_SimpleShp													= 530,
		BSSM_LAND4O4															= 531,
		BSSM_LAND4O4_Shp														= 532,
		BSSM_LAND4O4_Simple														= 533,
		BSSM_LAND4O4_SimpleShp													= 534,
		BSSM_LAND5O																= 535,
		BSSM_LAND5O_Shp															= 536,
		BSSM_LAND5O_Simple														= 537,
		BSSM_LAND5O_SimpleShp													= 538,
		BSSM_LAND5O4															= 539,
		BSSM_LAND5O4_Shp														= 540,
		BSSM_LAND5O4_Simple														= 541,
		BSSM_LAND5O4_SimpleShp													= 542,
		BSSM_LAND6O																= 543,
		BSSM_LAND6O_Shp															= 544,
		BSSM_LAND6O_Simple														= 545,
		BSSM_LAND6O_SimpleShp													= 546,
		BSSM_LAND6O4															= 547,
		BSSM_LAND6O4_Shp														= 548,
		BSSM_LAND6O4_Simple														= 549,
		BSSM_LAND6O4_SimpleShp													= 550,
		BSSM_LAND7O																= 551,
		BSSM_LAND7O_Shp															= 552,
		BSSM_LAND7O_Simple														= 553,
		BSSM_LAND7O_SimpleShp													= 554,
		BSSM_LAND7O4															= 555,
		BSSM_LAND7O4_Shp														= 556,
		BSSM_LAND7O4_Simple														= 557,
		BSSM_LAND7O4_SimpleShp													= 558,
		BSSM_LANDO_Am															= 559,
		BSSM_LANDLO_A															= 560,
		BSSM_2x_SIMPLESHADOW													= 561,
		BSSM_2x_SIMPLESHADOW_S													= 562,
		BSSM_2x_SIMPLESHADOW_LAND												= 563,
		BSSM_2x_SIMPLESHADOW_Sb													= 564,
		BSSM_ADT_Sbb															= 565,
		BSSM_DISTANT_TREE_BASE													= 566,
		BSSM_DISTANT_TREE_SILHOUETTE											= 567,
		BSSM_SKYBASEPRE															= 568,
		BSSM_SKY																= 569,
		BSSM_SKY_MOON_STARS_MASK												= 570,
		BSSM_SKY_STARS															= 571,
		BSSM_SKY_TEXTURE														= 572,
		BSSM_SKY_CLOUDS															= 573,
		BSSM_SKY_CLOUDS_UNDERWATER												= 574,
		BSSM_WATER_LOD															= 575,
		BSSM_WATER_LOD_NO_REFLECTIONS											= 576,
		BSSM_PARTICLE															= 577,
		BSSM_BOLT																= 578,
		BSSM_BEAM																= 579,
		BSSM_ENVMAP																= 580,
		BSSM_ENVMAP_Vc															= 581,
		BSSM_ENVMAP_S															= 582,
		BSSM_ENVMAP_SVc															= 583,
		BSSM_2x_ENVMAP															= 584,
		BSSM_2x_ENVMAP_S														= 585,
		BSSM_2x_ENVMAP_W														= 586,
		BSSM_2x_ENVMAP_EYE														= 587,
		BSSM_GEOMDECAL															= 588,
		BSSM_GEOMDECAL_S														= 589,
		BSSM_TEXEFFECT															= 590,
		BSSM_TEXEFFECT_S														= 591,
		BSSM_2x_TEXEFFECT														= 592,
		BSSM_2x_TEXEFFECT_S														= 593,
		BSSM_FOG																= 594,
		BSSM_FOG_A																= 595,
		BSSM_FOG_S																= 596,
		BSSM_FOG_SA																= 597,
		BSSM_FOG_Sb																= 598,
		BSSM_UNK_599															= 599,
		BSSM_UNK_600															= 600,
		BSSM_VFOG_1																= 601,
		BSSM_VFOG_2																= 602,
		BSSM_VFOG_3																= 603,
		BSSM_GRASS_DIRONLY_LF													= 604,
		BSSM_GRASS_DIRONLY_LV													= 605,
		BSSM_GRASS_DIRONLY_LFS													= 606,
		BSSM_GRASS_DIRONLY_LVS													= 607,
		BSSM_GRASS_DIRONLY_LFP													= 608,
		BSSM_GRASS_DIRONLY_LVP													= 609,
		BSSM_GRASS_DIRONLY_LFSP													= 610,
		BSSM_GRASS_DIRONLY_LVSP													= 611,
		BSSM_GRASS_DIRONLY_LFShp												= 612,
		BSSM_GRASS_DIRONLY_LVShp												= 613,
		BSSM_GRASS_DIRONLY_LFSShp												= 614,
		BSSM_GRASS_DIRONLY_LVSShp												= 615,
		BSSM_GRASS_DIRONLY_LFPShp												= 616,
		BSSM_GRASS_DIRONLY_LVPShp												= 617,
		BSSM_GRASS_DIRONLY_LFSPShp												= 618,
		BSSM_GRASS_DIRONLY_LVSPShp												= 619,
		BSSM_GRASS_DIRONLY_LFB													= 620,
		BSSM_GRASS_DIRONLY_LFSB													= 621,
		BSSM_GRASS_DIRONLY_LFPB													= 622,
		BSSM_GRASS_DIRONLY_LFSPB												= 623,
		BSSM_GRASS_1POINT_LF													= 624,
		BSSM_GRASS_1POINT_LV													= 625,
		BSSM_GRASS_1POINT_LFS													= 626,
		BSSM_GRASS_1POINT_LVS													= 627,
		BSSM_GRASS_1POINT_LFP													= 628,
		BSSM_GRASS_1POINT_LVP													= 629,
		BSSM_GRASS_1POINT_LFSP													= 630,
		BSSM_GRASS_1POINT_LVSP													= 631,
		BSSM_GRASS_1POINT_LFShp													= 632,
		BSSM_GRASS_1POINT_LVShp													= 633,
		BSSM_GRASS_1POINT_LFSShp												= 634,
		BSSM_GRASS_1POINT_LVSShp												= 635,
		BSSM_GRASS_1POINT_LFPShp												= 636,
		BSSM_GRASS_1POINT_LVPShp												= 637,
		BSSM_GRASS_1POINT_LFSPShp												= 638,
		BSSM_GRASS_1POINT_LVSPShp												= 639,
		BSSM_GRASS_1POINT_LFB													= 640,
		BSSM_GRASS_1POINT_LFSB													= 641,
		BSSM_GRASS_1POINT_LFPB													= 642,
		BSSM_GRASS_1POINT_LFSPB													= 643,
		BSSM_GRASS_SHADOW_L														= 644,
		BSSM_GRASS_SHADOW_LS													= 645,
		BSSM_GRASS_SHADOW_LB													= 646,
		BSSM_GRASS_SHADOW_LSB													= 647,
		BSSM_WATER_STENCIL														= 648,
		BSSM_WATER_STENCIL_Vc													= 649,
		BSSM_WATER_WADING														= 650,
		BSSM_WATER_WADING_NO_REFLECTIONS_NO_REFRACTIONS							= 651,
		BSSM_WATER_WADING_NO_REFRACTIONS										= 652,
		BSSM_WATER_WADING_NO_REFLECTIONS										= 653,
		BSSM_WATER_WADING_NO_DEPTH												= 654,
		BSSM_WATER_WADING_NO_DEPTH_NO_REFLECTIONS_NO_REFRACTIONS				= 655,
		BSSM_WATER_WADING_NO_DEPTH_NO_REFRACTIONS								= 656,
		BSSM_WATER_WADING_NO_DEPTH_NO_REFLECTIONS								= 657,
		BSSM_WATER_INTERIOR_WADING												= 658,
		BSSM_WATER_INTERIOR_WADING_NO_REFLECTIONS_NO_REFRACTIONS				= 659,
		BSSM_WATER_INTERIOR_WADING_NO_REFRACTIONS								= 660,
		BSSM_WATER_INTERIOR_WADING_NO_REFLECTIONS								= 661,
		BSSM_WATER_INTERIOR_WADING_NO_DEPTH										= 662,
		BSSM_WATER_INTERIOR_WADING_NO_DEPTH_NO_REFLECTIONS_NO_REFRACTIONS		= 663,
		BSSM_WATER_INTERIOR_WADING_NO_DEPTH_NO_REFRACTIONS						= 664,
		BSSM_WATER_INTERIOR_WADING_NO_DEPTH_NO_REFLECTIONS						= 665,
		BSSM_WATER_WADING_SPECULAR_LIGHTING										= 666,
		BSSM_WATER_WADING_Vc													= 667,
		BSSM_WATER_WADING_NO_REFLECTIONS_Vc										= 668,
		BSSM_WATER_WADING_NO_REFRACTIONS_Vc										= 669,
		BSSM_WATER_WADING_NO_REFLECTIONS_NO_REFRACTIONS_Vc						= 670,
		BSSM_WATER_WADING_NO_DEPTH_Vc											= 671,
		BSSM_WATER_WADING_NO_DEPTH_NO_REFLECTIONS_Vc							= 672,
		BSSM_WATER_WADING_NO_DEPTH_NO_REFRACTIONS_Vc							= 673,
		BSSM_WATER_WADING_NO_DEPTH_NO_REFLECTIONS_NO_REFRACTIONS_Vc				= 674,
		BSSM_WATER_INTERIOR_WADING_Vc											= 675,
		BSSM_WATER_INTERIOR_WADING_NO_REFLECTIONS_Vc							= 676,
		BSSM_WATER_INTERIOR_WADING_NO_REFRACTIONS_Vc							= 677,
		BSSM_WATER_INTERIOR_WADING_NO_REFLECTIONS_NO_REFRACTIONS_Vc				= 678,
		BSSM_WATER_INTERIOR_WADING_NO_DEPTH_Vc									= 679,
		BSSM_WATER_INTERIOR_WADING_NO_DEPTH_NO_REFLECTIONS_Vc					= 680,
		BSSM_WATER_INTERIOR_WADING_NO_DEPTH_NO_REFRACTIONS_Vc					= 681,
		BSSM_WATER_INTERIOR_WADING_NO_DEPTH_NO_REFLECTIONS_NO_REFRACTIONS_Vc	= 682,
		BSSM_WATER_WADING_SPECULAR_LIGHTING_Vc									= 683,
		BSSM_WATER																= 684,
		BSSM_WATER_NO_REFLECTIONS_NO_REFRACTIONS								= 685,
		BSSM_WATER_NO_REFRACTIONS												= 686,
		BSSM_WATER_NO_REFLECTIONS												= 687,
		BSSM_WATER_INTERIOR														= 688,
		BSSM_WATER_INTERIOR_NO_REFLECTIONS_NO_REFRACTIONS						= 689,
		BSSM_WATER_INTERIOR_NO_REFRACTIONS										= 690,
		BSSM_WATER_INTERIOR_NO_REFLECTIONS										= 691,
		BSSM_WATER_NODEPTH														= 692,
		BSSM_WATER_NODEPTH_NO_REFLECTIONS										= 693,
		BSSM_WATER_NODEPTH_NO_REFRACTIONS										= 694,
		BSSM_WATER_NODEPTH_NO_REFLECTIONS_NO_REFRACTIONS						= 695,
		BSSM_WATER_INTERIOR_NODEPTH												= 696,
		BSSM_WATER_INTERIOR_NODEPTH_NO_REFLECTIONS_NO_REFRACTIONS				= 697,
		BSSM_WATER_INTERIOR_NODEPTH_NO_REFRACTIONS								= 698,
		BSSM_WATER_INTERIOR_NODEPTH_NO_REFLECTIONS								= 699,
		BSSM_WATER_SPECULAR_LIGHTING											= 700,
		BSSM_WATER_UNDERWATER													= 701,
		BSSM_WATER_Vc															= 702,
		BSSM_WATER_NO_REFLECTIONS_NO_REFRACTIONS_Vc								= 703,
		BSSM_WATER_NO_REFRACTIONS_Vc											= 704,
		BSSM_WATER_NO_REFLECTIONS_Vc											= 705,
		BSSM_WATER_INTERIOR_Vc													= 706,
		BSSM_WATER_INTERIOR_NO_REFLECTIONS_NO_REFRACTIONS_Vc					= 707,
		BSSM_WATER_INTERIOR_NO_REFRACTIONS_Vc									= 708,
		BSSM_WATER_INTERIOR_NO_REFLECTIONS_Vc									= 709,
		BSSM_WATER_NODEPTH_Vc													= 710,
		BSSM_WATER_NODEPTH_NO_REFLECTIONS_Vc									= 711,
		BSSM_WATER_NODEPTH_NO_REFRACTIONS_Vc									= 712,
		BSSM_WATER_NODEPTH_NO_REFLECTIONS_NO_REFRACTIONS_Vc						= 713,
		BSSM_WATER_INTERIOR_NODEPTH_Vc											= 714,
		BSSM_WATER_INTERIOR_NODEPTH_NO_REFLECTIONS_NO_REFRACTIONS_Vc			= 715,
		BSSM_WATER_INTERIOR_NODEPTH_NO_REFRACTIONS_Vc							= 716,
		BSSM_WATER_INTERIOR_NODEPTH_NO_REFLECTIONS_Vc							= 717,
		BSSM_WATER_SPECULAR_LIGHTING_Vc											= 718,
		BSSM_PRECIPITATION_RAIN													= 719,
		BSSM_SKYBASEPOST														= 720,
		BSSM_SELFILLUM_SKY														= 721,
		BSSM_SKY_SUNGLARE														= 722,
		BSSM_SELFILLUM_SKY_SUN													= 723,
		BSSM_SELFILLUM_SKY_CLOUDS												= 724,
		BSSM_SELFILLUM_SKY_SKY_QUAD												= 725,
		BSSM_SELFILLUMALPHA														= 726,
		BSSM_SELFILLUMALPHA_S													= 727,
		BSSM_WATER_DEPTH														= 728,
		BSSM_WATER_DEPTH_S														= 729,
		BSSM_3XWATER_DEPTH														= 730,
		BSSM_3XWATER_DEPTH_S													= 731,
		BSSM_NLWATER_DEPTH														= 732,
		BSSM_NLWATER_DEPTH_S													= 733,
		BSSM_WATER_DEPTH_At														= 734,
		BSSM_WATER_DEPTH_SAt													= 735,
		BSSM_3XWATER_DEPTH_At													= 736,
		BSSM_3XWATER_DEPTH_SAt													= 737,
		BSSM_NLWATER_DEPTH_At													= 738,
		BSSM_NLWATER_DEPTH_At_S													= 739,
		BSSM_WATER_DEPTH_Vc														= 740,
		BSSM_WATER_DEPTH_SVc													= 741,
		BSSM_3XWATER_DEPTH_Vc													= 742,
		BSSM_3XWATER_DEPTH_SVc													= 743,
		BSSM_NLWATER_DEPTH_Vc													= 744,
		BSSM_NLWATER_DEPTH_Vc_S													= 745,
		BSSM_WATER_DEPTH_AtVc													= 746,
		BSSM_WATER_DEPTH_SAtVc													= 747,
		BSSM_3XWATER_DEPTH_AtVc													= 748,
		BSSM_3XWATER_DEPTH_SAtVc												= 749,
		BSSM_NLWATER_DEPTH_AtVc													= 750,
		BSSM_NLWATER_DEPTH_AtVc_S												= 751,
		BSSM_BLOOD_SPLATTER_FLARE												= 752,
		BSSM_BLOOD_SPLATTER														= 753,
		BSSM_SHADOWVOLUME_BACK													= 754,
		BSSM_SHADOWVOLUME_FRONT													= 755,
		BSSM_SHADOWVOLUME_WIRE													= 756,
		BSSM_TILE																= 757,
		BSSM_IMAGESPACE															= 758,
		BSSM_FINAL_PASS															= 759,
		BSSM_PASS_COUNT
	};

	enum LightingPasses : UInt32 {
		BSSM_PASS_NONE			= 0,
		BSSM_PASS_AMBIENT		= 1 << 0,
		BSSM_PASS_DIFFUSE		= 1 << 1,
		BSSM_PASS_TEXTURE		= 1 << 2,
		BSSM_PASS_SPECULAR		= 1 << 3,
		BSSM_PASS_SHADOW		= 1 << 4,
		BSSM_PASS_CANOPYSHADOW	= 1 << 5,
		BSSM_PASS_OPT			= 0x100,
		BSSM_PASS_ALL			= BSSM_PASS_AMBIENT | BSSM_PASS_DIFFUSE | BSSM_PASS_TEXTURE | BSSM_PASS_SPECULAR | BSSM_PASS_SHADOW | BSSM_PASS_CANOPYSHADOW | BSSM_PASS_OPT,
	};

	enum RenderMode : UInt32 {
		BSSM_RENDER_NORMAL			= 0,	// Renders everything as you'd expect
		BSSM_RENDER_UNK1			= 1,
		BSSM_RENDER_UNK2			= 2,
		BSSM_RENDER_UNK3			= 3,
		BSSM_RENDER_UNK4			= 4,
		BSSM_RENDER_UNK5			= 5,
		BSSM_RENDER_UNK6			= 6,
		BSSM_RENDER_DEPTH_MAP		= 7,
		BSSM_RENDER_CONST_ALPHA		= 8,	// Everything is green
		BSSM_RENDER_LOCAL_MAP		= 9,	// Renders vertex normals, skips landscape
		BSSM_RENDER_TILES			= 10,
		BSSM_RENDER_UNK11			= 11,
		BSSM_RENDER_NO_WATER_PASS	= 12,	// Skips water rendering
		BSSM_RENDER_UNK13			= 13,
		BSSM_RENDER_WATER_DEPTH		= 14,
		BSSM_RENDER_SILHOUETTE		= 15,	// Everything is black except for grass, sky and emissives
	};

	struct ShaderPackage {
		struct RawShader {
			char	cFileName[260];
			DWORD	shader;
		};

		const char*					pcPackagePath;
		DWORD						dword4;
		NiTStringMap<RawShader*>	kShaders;

		static ShaderPackage* GetSingleton() { return *(ShaderPackage**)0x11F9498; }
		RawShader* GetShader(const char* apcShaderName) {
			RawShader* pShader = nullptr;
			kShaders.GetAt(apcShaderName, pShader);
			return pShader;
		}
	};

	struct BSShaderMacro {
		const char* pcPath;
		D3DXMACRO	kMacros[9];
	};

	static UInt32 uiDebugMode;
	static bool bNoMips;
	static bool bHDRMult;

	static bool* const bIsHDR;
	static bool* const bIsLiteBrite;
	static bool* const bIsInInterior;
	static bool* const bImageSpaceEffects;
	static bool* const bUseRefractionShader;
	static bool* const bLODFadeInProgress;
	static bool* const bUseDepthBias;
	static bool* const bUseOptPasses;

	static float* const fDepthBias;
	static float* const fLODLandDrop;
	static float* const fLODFadeTimer;
	static float* const fTimers;

	static UInt32* const eShadowMode;
	static UInt32* const eGPUVendor;

	static Bitfield32* const uiEnabledPasses;
	static NiRect<float>* const kFramebufferViewport;
	static NiTexturePtr* const spCanopyShadowTexture;
	static NiTexturePtr* const spCanopyShadowMask;
	static NiPoint3* const kCullerCameraPos;
	static NiPoint3* const kCameraPos;
	static NiPoint4* const kLoadedRange;
	static NiCamera** const pCamera;

	static RenderMode* const eRenderMode;

	static BSRenderedTexture** pWaterRefractionTexture;

	static void SetCamera(NiCamera* apCamera);

	static ShadowSceneNode* GetShadowSceneNode(UInt32 aeType);

	static BSShaderAccumulator* GetAccumulator();
	static void SetAccumulator(BSShaderAccumulator* apAccumulator);

	static BSShaderAccumulator* GetCurrentAccumulator();

	static NiDX9Renderer* GetRenderer();

	static BSShader* GetShader(ShaderType aiShaderIndex);

	static void SetRenderMode15ShaderAccumulator(BSShaderAccumulator* apAccumulator);

	static UInt32 GetShaderModel(bool abPixel);

	static bool CanUseRefractionShader();

	static bool IsShadowPass();

	static void GetTexture(const char* apFilename, bool abLoadFile, NiPointer<NiTexture>& aspTexture, bool abCheckMips = true, bool abCubeMap = false);

	static void SetShader(NiGeometry* apGeometry, UInt32 aeFadeType, bool abKeepUV = false, bool abNoPrecache = false);
	static void SetShadersRecursively(NiAVObject* apObject, UInt32 aeFadeType, bool abKeepUV = false, bool abNoPrecache = false);
	static void AssignShaders(NiAVObject* apObject, bool abKeepUV = false, bool abNoPrecache = false);

	static UInt32 GetFadeType(NiAVObject* apObject);

	static SceneGraphType GetFogIndex();

	static void SetFogIndex(SceneGraphType acIndex);

	static void SetRenderMode(RenderMode auiRenderMode);

	static double GetTimer(bool abDelta);

	static void SetTimer(bool abDelta, double afTime);

	static void ClearShadowAccumCount();
	static BSShaderAccumulator* GetNextShadowAccumulator();

	static bool __cdecl SetLightingPasses(void* paramInfo, void* scriptData, void* thisObj, void* containingObj, void* scriptObj, void* eventList, int, void* opcodeOffsetPtr);

	static void __cdecl SetExternalEmittanceRecurse(NiAVObject* apObject, NiColor* apExternalEmittance);
	static TangentSpaceData* CreateTangentSpaceSimple(NiGeometry* apGeometry);
	static void ProcessQueuedLights();

	static bool ShouldShowCanopyShadowTexture();

	static NiTexturePtr* const GetHideSecretMap()			{ return (NiTexturePtr*)0x11F9528; }
	static NiTexturePtr* const GetAnisoMap()				{ return (NiTexturePtr*)0x11F9530; }
	static NiTexturePtr* const GetNormalMap()				{ return (NiTexturePtr*)0x11F9510; }
	static NiTexturePtr* const GetNormalGlossMap()			{ return (NiTexturePtr*)0x11F9518; }
	static NiTexturePtr* const GetArmorReflectionCubeMap()	{ return (NiTexturePtr*)0x11F95D4; }
	static NiTexturePtr* const GetEyeReflectionCubeMap()	{ return (NiTexturePtr*)0x11F9544; }
	static NiTexturePtr* const GetErrorMap()				{ return (NiTexturePtr*)0x11F9514; }
	static NiTexturePtr* const GetHeightMap()				{ return (NiTexturePtr*)0x11F951C; }
	static NiTexturePtr* const GetTexEffectMap()			{ return (NiTexturePtr*)0x11F952C; }
	static NiTexturePtr* const GetLODNoiseMap()				{ return (NiTexturePtr*)0x11F953C; }
	static NiTexturePtr* const GetEmptyNoiseMap()			{ return (NiTexturePtr*)0x11F9540; }
	static NiTexturePtr* const GetAttenuationXYZ()			{ return (NiTexturePtr*)0x11F9534; }

	static bool bDisabledMips[RenderPassType::BSSM_PASS_COUNT];
};