#include "TESForm.hpp"

const char* const TESForm::TypeNames[TESForm::kType_Count] = {
	"None",
	"TES4",
	"Group",
	"Game Setting",
	"Texture Set",
	"Menu Icon",
	"Global",
	"Class",
	"Faction",
	"Head Part",
	"Hair",
	"Eyes",
	"Race",
	"Sound",
	"Acoustic Space",
	"Skill",
	"Effect Setting",
	"Script",
	"Land Texture",
	"Enchantment Item",
	"Spell Item",
	"Activator",
	"Talking Activator",
	"Terminal",
	"Armor",
	"Book",
	"Clothing",
	"Container",
	"Door",
	"Ingredient Item",
	"Light",
	"Misc",
	"Static Object",
	"Static Collection",
	"Movable Static",
	"Placeable Water",
	"Grass",
	"Tree",
	"Flora",
	"Furniture",
	"Weapon",
	"Ammo",
	"NPC",
	"Creature",
	"Leveled Creature",
	"Leveled Character",
	"Key",
	"Alchemy Item",
	"Idle Marker",
	"Note",
	"Constructible Object",
	"Projectile",
	"Leveled Item",
	"Weather",
	"Climate",
	"Region",
	"NavMeshInfo Map",
	"Cell",
	"Reference",
	"Character",
	"Creature",
	"Missile Projectile",
	"Grenade Projectile",
	"Beam Projectile",
	"Flame Projectile",
	"WorldSpace",
	"Landscape",
	"NavMesh",
	"TLOD",
	"Topic",
	"Topic Info",
	"Quest",
	"Idle Form",
	"Package",
	"Combat Style",
	"Loading Screen",
	"Leveled Spell",
	"Animated Object",
	"Water Form",
	"Effect Shader",
	"TOFT",
	"Explosion",
	"Debris",
	"ImageSpace",
	"ImageSpaceModifier",
	"List Form",
	"Perk",
	"Body Part Data",
	"Addon Node",
	"Actor Value Info",
	"Radiation Stage",
	"Camera Shot",
	"Camera Path",
	"Voice Type",
	"Impact Data",
	"Impact Data Set",
	"Armature",
	"Encounter Zone",
	"Message",
	"Ragdoll",
	"Default Object Manager",
	"Lighting Template",
	"Music Type",
	"Weapon Mod",
	"Reputation",
	"Continuous Beam Projectile",
	"Recipe",
	"Recipe Category",
	"Casino Chips",
	"Casino",
	"Loading Screen Type",
	"Media Set",
	"Media Location Controller",
	"Challenge",
	"Ammo Effect",
	"Caravan Card",
	"Caravan Money",
	"Caravan Deck",
	"Dehydration Stage",
	"Hunger Stage",
	"Sleep Deprivation Stage"
};