#pragma once
#include <random>

inline const char* author[] {
	"",
	"",
	"",
	"Yvile's ",
	"Yvile's ",
	"Yvile's ",
	"Yvile's Yvile's ",
	"Yvile's Cobb's ",
	"Yvileapsis' ",
	"Yvileapsis' ",
	"Yvileapsis' ",
	"Yvileapsis' Cobb's ",
	"Yvileapsis' Yvile's ",
	"Joe Cobb's ",
	"(Not Really) Cobb's ",
	"Trooper's ",
	"Pepe's ",
	"Todd Howard's ",
	"xNVSE Discord's ",
	"The Great and Powerful Trixie's ",
	"ModdingLinked: ",
	"Karut's ",
	"Todd's ",
	"Better Gaem's ",
	"Nobark's ",
	"Thankfully not karut's ",
	"The most hated ",
	"Woah, is that a ",
	"Where did you get this ",
	"Wall's ",
	"lStewieAl's ",
	"Someguy's ",
	"Vanilla Enhanced ",
	"Vanilla "
	"Hit - ",
	"B42 ",
	"TTW Compatible",
	"JIP ",
	"Simple ",
	"AI Generated ",
	"Enhanced ",
	"Consistent ",
	"Broken ",
};

inline const char* names[] {
	"Crash Logger",
	"Crash Logger",
	"Crash Logger",
	"Crash Logger",
	"Crash Logger",
	"Crash Logger",
	"Crash Logger",
	"Crash Logger",
	"Crash Logger",
	"Crash Blogger",
	"AAAAAAA IT CRASHED",
	"Obsurdian Ls Logger",
	"Bugthesda Ls Logger",
	"Rash Clogger",
	"Brad Boimler (God, I f*cking hate that show)",
	"Abandonwarebytes",
	"Name Coiner",
	"Crash Logger 2: Electric Boogaloo",
	"Crash Logger: Enhanced Edition",
	"Project Crashlogger",
	"yCL",
	"Fallout-Crashing-Logging Convergence",
	"Great and Powerful Crash Logger",
	"Program with useless data in it",
	"NVAC",
	"Slop",
	"Hopium Dispenser",
	"Mod Blamer",
	"Nonsene Generator",
	"Skill Issue Catcher",
	"Crash Extender",
	"Crash Overhaul",
};

inline const char* edition[] {
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	": Ultimate Edition",
	" NVSE",
	" (NVSE)",
	" Tweaks",
	" (April's Fools Edition)",
	" (Unfunny Random Names Edition)",
	" (Todd Howard Ruined Fallout Edition)",
	" (Soyvellone and JSoyer Edition)",
	" (Trochili Edition)",
	" (Skill Issue Edition)",
	" (Works On My Machine Edition)"
	" (I'd Rather Be Playing Starfield Edition)",
	" (Downgrade Edition)",
	" (:snig: edition)",
	" (100 endings edition)",
	" (16 times the detail edition)"
	": Roybug Until Proven Otherwise",
	": Just Go Away",
	": At Least With This Upload You Made Some Changes To The Original Mod",
	": FalloutNV.exe has fallen, billion bugs must die",
	": Born To Crash / GameBryo is a F*CK / Fix Em All",
	": I Am Crash Man / 80,101,112,101,103,108,97,114,101 fixed bugs",
	": Just when I thought I was out, they pulled me back in!",
	": Radio Free FalloutNV.exe",
	": Theoretical Degree in Reverse Engineering",
	": Nice Try, Carxt", 
	": FIX IT NOW NOW NOW",
	": Tried Following Viva New Vegas Guide Yet?",
	": ITS NOT A FUCKING HAT",
	": No Job Edition",
	" Spoiler: it's not a memory leak",
	" (Unreal Engine 5 Edition)",
	" (Enhanced with AI Edition)",
	": You should play Fallout 4 Instead",
	": You are not going to fix it, you know.",
	": Just Reinstall Windows",
	": Did you try turning it off and on again?",
	": Play on PS3 instead",
	": I ran out of bits",
	": Feed me into ChatGPT so you don't have to use your brain to read words",
	": Try using Linux",
	": This is what happens when you don't use smart pointers",
	" (Spontaneous Bit Flip Edition)",
	": It's time to take a break",
	": Stop using mods, now",
	": Have you tried disabling NVSE?",
	": You are missing Sexout",
	": The engine is NOT Gamebryo! Edition",
	" (This wouldn't have happened on the Creation Engine)",
	" (Blame Bethesda Edition)",
	": Devs added this crash deliberately",
	": This one is personal",
	": Ignore this one",
	" (You call this a log?)",
	" (I know what you are)",
	"... or is it?",
	" Plus",
	" ESPless",
	" - Translation",
	" AAAA Edition",
	": Does anyone even read these?",
	" (I can't believe it's a crash!)",
	": Reinstall your game 100 times, that will do it",
	": Go drink some water",
	": You call that a modded game?",
};

void GetName(char* buffer, size_t bufferSize)
{
	std::random_device dev;
	srand(dev());

	const char* authorName = author[std::rand() % ARRAYSIZE(author)];
	const char* loggerName = names[std::rand() % ARRAYSIZE(names)];
	const char* loggerEdition = edition[std::rand() % ARRAYSIZE(edition)];
	sprintf_s(buffer, bufferSize, "%s%s%s", authorName, loggerName, loggerEdition);
}
